language: ruby
cache:
  - bundler
  - node_modules
sudo: required
addons:
  chrome: stable
rvm:
  - "2.4.5"
env:
  - DIR=models
  - DIR=integration
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm install -g coffeelint
  - npm install -g istanbul
  - npm install -g codecov
services: mongodb
bundler_args: --without test development
before_script:
  - git config --global user.email "travis@travis.ci"
  - git config --global user.name "Travis CI"
  - bundle install
  - wget http://chromedriver.storage.googleapis.com/2.44/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /tmp/chromedriver
  - export PATH=$PATH:/tmp/chromedriver
  - bundle exec rake teaspoon DIR=$DIR
  - codecov
  - yarn install
  - yarn audit
notifications:
  email:
    recipients:
      - healthcare-ci@googlegroups.com
    on_failure: change
